# Generated by Django 2.2.6 on 2019-11-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_record_slug'),
    ]

    operations = [
        migrations.RunSQL("""update feed_record set slug=title""")
    ]
